# IMPORT IMPORANT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Introduction
This dataset contains the information about the movie. 
For a movie to be commercial success,it depends on various factors like,  
movie name,direcctor,rating ,genre, metascore,rating, votes and gross are very important factor 
to measur the movie success

# Background

A commercial success movie not only entertains audience, but also enables film companies to gain tremendous profit. A lot of factors such as good directors, experienced actors are considerable for creating good movies. However, famous directors and actors can always bring an expected box-office income but cannot guarantee a highly rated imdb score.

# Description of dataset attributes

1.Movie Name= name of movie is given in this 

2.Year of Release= releasing year are given in this

3.Watch Time= total time taken by movie

4.Movie Rating= rating of movie given by public

5.Metascore of movie= given metascore

6.genres= Film categorization like ‘Animation’, ‘Comedy’, ‘Romance’, ‘Horror’, ‘Sci-Fi’, ‘Action’, ‘Family’

7.Votes=a vote given by public

8.description= full details about movie 

9.director=name of the movie  director

10.star= actors name 

11. gross=Gross earning of the movie in dollars(millions) 

# Read Csv file

Data preprocessing

In [2]:
movie_df=pd.read_csv('final_movie.csv')

#Displaying the first 5 records


In [3]:
movie_df.head()

Movie Name  Year of Release  \
0                                    The Dark Knight             2008   
1      The Lord of the Rings: The Return of the King             2003   
2                Spider-Man: Across the Spider-Verse             2023   
3                                          Inception             2010   
4  The Lord of the Rings: The Fellowship of the Ring             2001   

   Watch Time  Movie Rating  Metascore of movie  \
0         152           9.0                  84   
1         201           9.0                  94   
2         140           8.9                  86   
3         148           8.8                  74   
4         178           8.8                  92   

                                    genre    Votes  \
0          ['Action', ' Crime', ' Drama']  2747816   
1      ['Action', ' Adventure', ' Drama']  1901636   
2  ['Animation', ' Action', ' Adventure']   192310   
3     ['Action', ' Adventure', ' Sci-Fi']  2438666   
4      ['Action', ' Adventure', ' Drama']  1929939   

                                         Description  \
0  When the menace known as the Joker wreaks havo...   
1  Gandalf and Aragorn lead the World of Men agai...   
2  Miles Morales catapults across the Multiverse,...   
3  A thief who steals corporate secrets through t...   
4  A meek Hobbit from the Shire and eight compani...   

                                            Director  \
0                                  Christopher Nolan   
1                                      Peter Jackson   
2  Directors:Joaquim Dos Santos, Kemp Powers, Jus...   
3                                  Christopher Nolan   
4                                      Peter Jackson   

                                                Star   Gross  
0  ['Christian Bale', 'Heath Ledger', 'Aaron Eckh...  534.86  
1  ['Elijah Wood', 'Viggo Mortensen', 'Ian McKell...  377.85  
2  ['Shameik Moore', 'Hailee Steinfeld', 'Brian T...    0.00  
3  ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ...  292.58  
4  ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom...  315.54

In [4]:
#Shape of the dataset (no of rows and no of columns)


movie_df.shape

(500, 11)

#info of the movie dataset

In [5]:
movie_df.info

<bound method DataFrame.info of                                             Movie Name  Year of Release  \
0                                      The Dark Knight             2008   
1        The Lord of the Rings: The Return of the King             2003   
2                  Spider-Man: Across the Spider-Verse             2023   
3                                            Inception             2010   
4    The Lord of the Rings: The Fellowship of the Ring             2001   
..                                                 ...              ...   
495                 Kimetsu no Yaiba: Mugen Ressha-Hen             2020   
496                        Baahubali 2: The Conclusion             2017   
497                                 Gangs of Wasseypur             2012   
498                                            Yôjinbô             1961   
499                           Uri: The Surgical Strike             2019   

     Watch Time  Movie Rating  Metascore of movie  \
0           15

In [6]:
#columns of the dataset

movie_df.columns

Index(['Movie Name', 'Year of Release', 'Watch Time', 'Movie Rating',
       'Metascore of movie', 'genre', 'Votes', 'Description', 'Director',
       'Star', 'Gross'],
      dtype='object')

In [7]:
#Displaying the data type of the dataset attributes 

movie_df.dtypes

Movie Name             object
Year of Release         int64
Watch Time              int64
Movie Rating          float64
Metascore of movie      int64
genre                  object
Votes                   int64
Description            object
Director               object
Star                   object
Gross                 float64
dtype: object

#Five point summary for the numerical columns in the dataset


In [8]:
movie_df.describe()

Year of Release  Watch Time  Movie Rating  Metascore of movie  \
count       500.000000  500.000000    500.000000          500.000000   
mean       2002.700000  147.920000      8.422000           60.000000   
std          18.646861   33.975023      0.227639           34.960613   
min        1954.000000  101.000000      8.200000            0.000000   
25%        1991.000000  130.000000      8.200000           58.000000   
50%        2005.000000  140.000000      8.350000           73.500000   
75%        2019.000000  163.000000      8.600000           85.000000   
max        2023.000000  321.000000      9.000000           98.000000   

              Votes       Gross  
count  5.000000e+02  500.000000  
mean   7.924391e+05  175.404800  
std    6.992853e+05  225.842718  
min    3.158000e+04    0.000000  
25%    1.256580e+05    0.270000  
50%    6.578050e+05   70.305000  
75%    1.197669e+06  292.580000  
max    2.747816e+06  858.370000

In [9]:
#shape of dataset
movie_df.shape

(500, 11)

In [10]:
#check the null value
movie_df.isnull().sum()

Movie Name            0
Year of Release       0
Watch Time            0
Movie Rating          0
Metascore of movie    0
genre                 0
Votes                 0
Description           0
Director              0
Star                  0
Gross                 0
dtype: int64

# drop those value which is not important 

In [11]:
movie_df.drop('Movie Name',axis=1,inplace=True)

In [12]:
movie_df.drop('genre',axis=1,inplace=True)

In [13]:
movie_df.drop('Description',axis=1,inplace=True)

In [14]:
movie_df.drop('Director',axis=1,inplace=True)

In [15]:
movie_df.drop('Star',axis=1,inplace=True)

In [16]:
movie_df=movie_df.dropna()

# Drop the duplicate value

In [17]:

movie_df.drop_duplicates(inplace=True)
movie_df.shape

(50, 6)

In [18]:
movie_df.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes  \
0             2008         152           9.0                  84  2747816   
1             2003         201           9.0                  94  1901636   
2             2023         140           8.9                  86   192310   
3             2010         148           8.8                  74  2438666   
4             2001         178           8.8                  92  1929939   

    Gross  
0  534.86  
1  377.85  
2    0.00  
3  292.58  
4  315.54

In [19]:
#We need to categorize the imdb values in the range of 0-300,300-400,400-500 and 500-600 to mark them as the bad,average,good and excellent movies respectively


movie_df["imdb_binned_gross"]=pd.cut(movie_df['Gross'], bins=[0,300,400,500,600], right=True, labels=False)+1


In [20]:
#Dropping the Gross column as it is being replaced with the imdb_binned_gross values 


movie_df.drop('Gross',axis=1,inplace=True)

In [21]:
movie_df.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes  \
0             2008         152           9.0                  84  2747816   
1             2003         201           9.0                  94  1901636   
2             2023         140           8.9                  86   192310   
3             2010         148           8.8                  74  2438666   
4             2001         178           8.8                  92  1929939   

   imdb_binned_gross  
0                4.0  
1                2.0  
2                NaN  
3                1.0  
4                2.0

In [22]:
#Removing the NaN value with the dropna

movie_df=movie_df.dropna()

In [23]:
movie_df.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes  \
0             2008         152           9.0                  84  2747816   
1             2003         201           9.0                  94  1901636   
3             2010         148           8.8                  74  2438666   
4             2001         178           8.8                  92  1929939   
5             2002         179           8.8                  87  1716048   

   imdb_binned_gross  
0                4.0  
1                2.0  
3                1.0  
4                2.0  
5                2.0

In [24]:
movie_df.columns

Index(['Year of Release', 'Watch Time', 'Movie Rating', 'Metascore of movie',
       'Votes', 'imdb_binned_gross'],
      dtype='object')

#create x and y axis

In [25]:
X=movie_df.iloc[:,:-1]
y=movie_df.iloc[:,-1]

In [26]:
X.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes
0             2008         152           9.0                  84  2747816
1             2003         201           9.0                  94  1901636
3             2010         148           8.8                  74  2438666
4             2001         178           8.8                  92  1929939
5             2002         179           8.8                  87  1716048

In [27]:
y.head()

0    4.0
1    2.0
3    1.0
4    2.0
5    2.0
Name: imdb_binned_gross, dtype: float64

# train test split 

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=100)

# feature scalling

# StandardScaler

In [29]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [30]:
X_test

array([[ 0.42753128, -0.05142512, -0.97200507,  0.10249154,  0.6151548 ],
       [ 1.38353874, -0.13903829, -0.97200507, -2.43614499, -1.52633718],
       [-0.93819365,  0.91231972, -0.97200507,  1.08167991, -1.43458975],
       [ 0.0178138 , -0.22665145,  1.17762152,  0.21129024,  1.28893461],
       [ 0.29095879,  2.62077648,  2.46739748,  0.9728812 ,  1.18225104],
       [ 1.31525249, -1.05897654, -0.11215443,  0.71901755, -0.7226961 ],
       [-1.07476614, -0.44568437, -0.54207975, -0.3327033 , -0.02354745],
       [ 1.45182498, -1.05897654, -0.97200507,  0.17502401, -1.52945916],
       [-0.11875869, -0.31426462, -0.54207975,  0.32008895, -1.02008922],
       [-1.27962488, -0.75233046,  1.17762152,  0.53768637,  0.33995978],
       [-3.05506729,  2.88361598,  0.74769621,  1.11794615, -1.10238207]])

In [31]:
y_test

38    1.0
49    1.0
44    1.0
6     1.0
1     2.0
17    1.0
27    2.0
45    1.0
28    1.0
7     1.0
11    1.0
Name: imdb_binned_gross, dtype: float64

# classification  model selection

# LogisticRegression

In [32]:
from sklearn.linear_model import LogisticRegression
logit =LogisticRegression()
logit.fit(X_train,np.ravel(y_train,order='C'))
y_pred=logit.predict(X_test)

# Confusion matrix for logistic regression

In [33]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[8 1]
 [1 1]]
Accuracy: 0.8181818181818182


# KNeighbrosClassifier(KNN)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=22)
knn.fit(X_train, np.ravel(y_train,order='C'))
knnpred = knn.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, knnpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, knnpred))

[[9 0]
 [2 0]]
Accuracy: 0.8181818181818182


# SVC(suport vector classifier)

In [35]:
from sklearn.svm import SVC
svc= SVC(kernel = 'sigmoid')
svc.fit(X_train, np.ravel(y_train,order='C'))
svcpred = svc.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, svcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, svcpred))

[[8 1]
 [2 0]]
Accuracy: 0.7272727272727273


# Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
gaussiannb= GaussianNB()
gaussiannb.fit(X_train, np.ravel(y_train,order='C'))
gaussiannbpred = gaussiannb.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, gaussiannbpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, gaussiannbpred))

[[8 0 1]
 [1 1 0]
 [0 0 0]]
Accuracy: 0.8181818181818182


# Descision tree classifier

In [37]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(criterion='gini') #criterion = entopy, gini
dtree.fit(X_train, np.ravel(y_train,order='C'))
dtreepred = dtree.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, dtreepred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, dtreepred))

[[8 0 1]
 [1 1 0]
 [0 0 0]]
Accuracy: 0.8181818181818182


# ADABOOST

In [38]:
from sklearn.ensemble import AdaBoostClassifier
abcl = AdaBoostClassifier(base_estimator=dtree, n_estimators=60)
abcl=abcl.fit(X_train,np.ravel(y_train,order='C'))
abcl_pred=abcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, abcl_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, abcl_pred))

[[8 0 1]
 [1 1 0]
 [0 0 0]]
Accuracy: 0.8181818181818182


# RandomForestClassifier

In [39]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200)#criterion = entopy,gini
rfc.fit(X_train, np.ravel(y_train,order='C'))
rfcpred = rfc.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, rfcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, rfcpred))

[[9 0]
 [1 1]]
Accuracy: 0.9090909090909091


In [40]:
#create new dataset and drop imdb_binned_gross

new_movie_df=movie_df.pop("imdb_binned_gross")

# BaggingClassifier

In [41]:

from sklearn.ensemble import BaggingClassifier
bgcl = BaggingClassifier(n_estimators=60, max_samples=.7 , oob_score=True)

bgcl = bgcl.fit(movie_df, new_movie_df)
print(bgcl.oob_score_)

0.7941176470588235


# Grandientboost

In [42]:
from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(n_estimators = 50, learning_rate = 0.09, max_depth=5)
gbcl = gbcl.fit(X_train,np.ravel(y_train,order='C'))
test_pred = gbcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, test_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, test_pred))

[[9 0]
 [1 1]]
Accuracy: 0.9090909090909091


# Model Comparision

In [43]:
from sklearn.metrics import classification_report

print('Logistic  Reports\n',classification_report(y_test, y_pred))
print('KNN Reports\n',classification_report(y_test, knnpred))
print('SVC Reports\n',classification_report(y_test, svcpred))
print('Naive BayesReports\n',classification_report(y_test, gaussiannbpred))
print('Decision Tree Reports\n',classification_report(y_test, dtreepred))
print('Ada Boosting\n',classification_report(y_test, abcl_pred))
print('Random Forests Reports\n',classification_report(y_test, rfcpred))
print('Bagging Clasifier',bgcl.oob_score_) 
print('Gradient Boosting',classification_report(y_test, test_pred))

Logistic  Reports
               precision    recall  f1-score   support

         1.0       0.89      0.89      0.89         9
         2.0       0.50      0.50      0.50         2

    accuracy                           0.82        11
   macro avg       0.69      0.69      0.69        11
weighted avg       0.82      0.82      0.82        11

KNN Reports
               precision    recall  f1-score   support

         1.0       0.82      1.00      0.90         9
         2.0       0.00      0.00      0.00         2

    accuracy                           0.82        11
   macro avg       0.41      0.50      0.45        11
weighted avg       0.67      0.82      0.74        11

SVC Reports
               precision    recall  f1-score   support

         1.0       0.80      0.89      0.84         9
         2.0       0.00      0.00      0.00         2

    accuracy                           0.73        11
   macro avg       0.40      0.44      0.42        11
weighted avg       0.65      

C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-p

# now we started prediction on vote

In [44]:
movie=pd.read_csv('final_movie.csv')

In [45]:
movie.head()

Movie Name  Year of Release  \
0                                    The Dark Knight             2008   
1      The Lord of the Rings: The Return of the King             2003   
2                Spider-Man: Across the Spider-Verse             2023   
3                                          Inception             2010   
4  The Lord of the Rings: The Fellowship of the Ring             2001   

   Watch Time  Movie Rating  Metascore of movie  \
0         152           9.0                  84   
1         201           9.0                  94   
2         140           8.9                  86   
3         148           8.8                  74   
4         178           8.8                  92   

                                    genre    Votes  \
0          ['Action', ' Crime', ' Drama']  2747816   
1      ['Action', ' Adventure', ' Drama']  1901636   
2  ['Animation', ' Action', ' Adventure']   192310   
3     ['Action', ' Adventure', ' Sci-Fi']  2438666   
4      ['Action', ' Adventure', ' Drama']  1929939   

                                         Description  \
0  When the menace known as the Joker wreaks havo...   
1  Gandalf and Aragorn lead the World of Men agai...   
2  Miles Morales catapults across the Multiverse,...   
3  A thief who steals corporate secrets through t...   
4  A meek Hobbit from the Shire and eight compani...   

                                            Director  \
0                                  Christopher Nolan   
1                                      Peter Jackson   
2  Directors:Joaquim Dos Santos, Kemp Powers, Jus...   
3                                  Christopher Nolan   
4                                      Peter Jackson   

                                                Star   Gross  
0  ['Christian Bale', 'Heath Ledger', 'Aaron Eckh...  534.86  
1  ['Elijah Wood', 'Viggo Mortensen', 'Ian McKell...  377.85  
2  ['Shameik Moore', 'Hailee Steinfeld', 'Brian T...    0.00  
3  ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ...  292.58  
4  ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom...  315.54

In [46]:
movie.columns

Index(['Movie Name', 'Year of Release', 'Watch Time', 'Movie Rating',
       'Metascore of movie', 'genre', 'Votes', 'Description', 'Director',
       'Star', 'Gross'],
      dtype='object')

In [47]:
movie.describe()

Year of Release  Watch Time  Movie Rating  Metascore of movie  \
count       500.000000  500.000000    500.000000          500.000000   
mean       2002.700000  147.920000      8.422000           60.000000   
std          18.646861   33.975023      0.227639           34.960613   
min        1954.000000  101.000000      8.200000            0.000000   
25%        1991.000000  130.000000      8.200000           58.000000   
50%        2005.000000  140.000000      8.350000           73.500000   
75%        2019.000000  163.000000      8.600000           85.000000   
max        2023.000000  321.000000      9.000000           98.000000   

              Votes       Gross  
count  5.000000e+02  500.000000  
mean   7.924391e+05  175.404800  
std    6.992853e+05  225.842718  
min    3.158000e+04    0.000000  
25%    1.256580e+05    0.270000  
50%    6.578050e+05   70.305000  
75%    1.197669e+06  292.580000  
max    2.747816e+06  858.370000

In [48]:
movie.drop('Movie Name',axis=1,inplace=True)
movie.drop('genre',axis=1,inplace=True)
movie.drop('Description',axis=1,inplace=True)
movie.drop('Director',axis=1,inplace=True)
movie.drop('Star',axis=1,inplace=True)
movie.drop('Gross',axis=1,inplace=True)

In [49]:
movie.drop_duplicates(inplace=True)
movie.shape

(50, 5)

In [50]:
movie.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes
0             2008         152           9.0                  84  2747816
1             2003         201           9.0                  94  1901636
2             2023         140           8.9                  86   192310
3             2010         148           8.8                  74  2438666
4             2001         178           8.8                  92  1929939

In [51]:
movie["imdb_binned_votes"]=pd.cut(movie['Votes'], bins=[0,100000,300000,1000000,5000000], right=True, labels=False)+1


In [52]:
movie.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie    Votes  \
0             2008         152           9.0                  84  2747816   
1             2003         201           9.0                  94  1901636   
2             2023         140           8.9                  86   192310   
3             2010         148           8.8                  74  2438666   
4             2001         178           8.8                  92  1929939   

   imdb_binned_votes  
0                  4  
1                  4  
2                  2  
3                  4  
4                  4

In [53]:
movie=movie.dropna()

In [54]:
movie.drop('Votes',axis=1,inplace=True)
movie.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie  \
0             2008         152           9.0                  84   
1             2003         201           9.0                  94   
2             2023         140           8.9                  86   
3             2010         148           8.8                  74   
4             2001         178           8.8                  92   

   imdb_binned_votes  
0                  4  
1                  4  
2                  2  
3                  4  
4                  4

In [55]:
movie.columns

Index(['Year of Release', 'Watch Time', 'Movie Rating', 'Metascore of movie',
       'imdb_binned_votes'],
      dtype='object')

In [56]:
X=movie.iloc[:,:-1]
y=movie.iloc[:,-1]

In [57]:
X.head()

Year of Release  Watch Time  Movie Rating  Metascore of movie
0             2008         152           9.0                  84
1             2003         201           9.0                  94
2             2023         140           8.9                  86
3             2010         148           8.8                  74
4             2001         178           8.8                  92

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [59]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [60]:
X_test

array([[-0.22874392, -0.35483012,  1.23550544,  0.41274459],
       [-0.74195144, -0.59781162, -1.08937039,  0.19912447],
       [-0.53666843, -0.59781162, -1.08937039,  0.27923201],
       [-0.33138542, -0.40882601, -0.62439522,  0.49285213],
       [ 0.07918059, -0.4628219 , -1.08937039,  0.11901692],
       [ 0.79767111, -0.30083424, -1.08937039, -1.536539  ],
       [-0.07478167,  0.80608148,  1.70048061,  0.7865798 ],
       [ 0.95163336,  0.6980897 , -0.62439522, -1.536539  ],
       [-0.89591369, -0.32783218, -0.15942006,  0.70647225],
       [-0.02346091, -1.02977873, -1.08937039,  0.30593453],
       [ 0.23314284,  0.07713698,  2.63043095,  0.70647225],
       [-2.53817774,  1.56202392,  0.77053028,  1.08030746],
       [ 0.43842585,  0.40111231, -0.15942006,  0.54625716],
       [ 0.84899186, -0.86779107, -1.08937039,  0.38604207],
       [ 0.07918059, -0.24683835, -1.08937039,  0.33263704]])

In [61]:
y_test

6     4
36    3
37    4
28    3
43    4
49    1
5     4
33    1
20    3
42    4
0     4
11    3
18    4
45    1
38    4
Name: imdb_binned_votes, dtype: int64

# LOGISTIC REGRESSION

In [62]:
from sklearn.linear_model import LogisticRegression
logit =LogisticRegression()
logit.fit(X_train,np.ravel(y_train,order='C'))
y_pred=logit.predict(X_test)

# CONFUSION METRICS

In [63]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[1 1 1 0]
 [0 0 0 0]
 [0 0 2 2]
 [0 0 4 4]]
Accuracy: 0.4666666666666667


# KNEIGHBROSCLASSIFIER(KNN)

In [64]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=22)
knn.fit(X_train, np.ravel(y_train,order='C'))
knnpred = knn.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, knnpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, knnpred))

[[0 3 0]
 [0 0 4]
 [0 2 6]]
Accuracy: 0.4


# SVC

In [65]:
from sklearn.svm import SVC
svc= SVC(kernel = 'sigmoid')
svc.fit(X_train, np.ravel(y_train,order='C'))
svcpred = svc.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, svcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, svcpred))

[[0 2 1 0]
 [0 0 0 0]
 [0 0 2 2]
 [0 0 4 4]]
Accuracy: 0.4


# GaussianNB

In [66]:

from sklearn.naive_bayes import GaussianNB
gaussiannb= GaussianNB()
gaussiannb.fit(X_train, np.ravel(y_train,order='C'))
gaussiannbpred = gaussiannb.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, gaussiannbpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, gaussiannbpred))

[[1 1 1 0]
 [0 0 0 0]
 [0 0 3 1]
 [0 0 4 4]]
Accuracy: 0.5333333333333333


# DecissionTreeClassifier

In [67]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(criterion='gini') #criterion = entopy, gini
dtree.fit(X_train, np.ravel(y_train,order='C'))
dtreepred = dtree.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, dtreepred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, dtreepred))

[[1 1 1 0]
 [0 0 0 0]
 [1 0 2 1]
 [0 0 4 4]]
Accuracy: 0.4666666666666667


# AdaBoostClassifier

In [68]:
from sklearn.ensemble import AdaBoostClassifier
abcl = AdaBoostClassifier(base_estimator=dtree, n_estimators=60)
abcl=abcl.fit(X_train,np.ravel(y_train,order='C'))
abcl_pred=abcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, abcl_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, abcl_pred))

[[1 1 1 0]
 [0 0 0 0]
 [1 0 2 1]
 [0 0 3 5]]
Accuracy: 0.5333333333333333


# RandomForestClassifier

In [69]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200)#criterion = entopy,gini
rfc.fit(X_train, np.ravel(y_train,order='C'))
rfcpred = rfc.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, rfcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, rfcpred))

[[0 2 1 0]
 [0 0 0 0]
 [0 0 2 2]
 [0 0 4 4]]
Accuracy: 0.4


create new table

In [70]:
new_movie=movie.pop("imdb_binned_votes")

# BaggingClassifier

In [71]:

from sklearn.ensemble import BaggingClassifier
bgcl = BaggingClassifier(n_estimators=60, max_samples=.7 , oob_score=True)

bgcl = bgcl.fit(movie, new_movie)
print(bgcl.oob_score_)

0.54


# GradientBoostingClassifier

In [72]:
from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(n_estimators = 50, learning_rate = 0.09, max_depth=5)
gbcl = gbcl.fit(X_train,np.ravel(y_train,order='C'))
test_pred = gbcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, test_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, test_pred))

[[1 1 1 0]
 [0 0 0 0]
 [0 0 1 3]
 [0 0 1 7]]
Accuracy: 0.6


# Model Comparision

In [73]:
from sklearn.metrics import classification_report

print('Logistic  Reports\n',classification_report(y_test, y_pred))
print('KNN Reports\n',classification_report(y_test, knnpred))
print('SVC Reports\n',classification_report(y_test, svcpred))
print('Naive BayesReports\n',classification_report(y_test, gaussiannbpred))
print('Decision Tree Reports\n',classification_report(y_test, dtreepred))
print('Ada Boosting\n',classification_report(y_test, abcl_pred))
print('Random Forests Reports\n',classification_report(y_test, rfcpred))
print('Bagging Clasifier',bgcl.oob_score_) 
print('Gradient Boosting',classification_report(y_test, test_pred))

Logistic  Reports
               precision    recall  f1-score   support

           1       1.00      0.33      0.50         3
           2       0.00      0.00      0.00         0
           3       0.29      0.50      0.36         4
           4       0.67      0.50      0.57         8

    accuracy                           0.47        15
   macro avg       0.49      0.33      0.36        15
weighted avg       0.63      0.47      0.50        15

KNN Reports
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         4
           4       0.60      0.75      0.67         8

    accuracy                           0.40        15
   macro avg       0.20      0.25      0.22        15
weighted avg       0.32      0.40      0.36        15

SVC Reports
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.00      0

C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ajit Kumar\anaconda3\lib\site-packages\sklearn\metrics\

# Conclusion

# 🤗🤗🤗🤗

we predict on both gross and vote and we have worked on so many tools in this project like,logistic regression,cnf,KNN,SVC,GaussianNB,DT many more an get so empressive accuracy value of imdb.i learn so many things with the help of this project and its to much helpfull for my experience.Thank you so much to sir or mam who provided this type of project...thank you💁💁💁